apiVersion: v1
kind: Secret
metadata:
  name: post-service-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  DB_NAME: cG9zdGdyZXM=         
  DB_SERVER: cG9zdGdyZXNxbC1kYg==
  DB_PORT: ODA5MA==
  ACTIVE_PROFILE: cHJvZA==