apiVersion: v1
kind: Secret
metadata:
  name: post-service-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  DB_NAME: cG9zdGdyZXM=         
  DB_SERVER: cG9zdGdyZXNxbA==
  DB_PORT: NTQzMg==