name: "Terraform CI/CD Github"
 
on:
 push:
   branches:
   - main
   paths-ignore:
   - terraform/kubernetes
 pull_request:
   branches:
   - main
   paths-ignore:
   - terraform/kubernetes

jobs:
 terraform:
   name: "Terraform Infrastructure"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       working-directory: ./terraform
 
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
    
     - name: Terraform init
       id: init
       run: terraform init
    
     - name: Terraform validate
       id: validate
       run: terraform validate
 
     - name: Terraform plan
       id: plan
       if: github.event_name == 'pull_request'
       run: terraform plan -no-color -input=false
       continue-on-error: true

     - name: Terraform Apply
       run: terraform apply -auto-approve -input=false